[build]
  publish = "public"
  command = "npm install"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/verify-diploma"
  to = "/.netlify/functions/verify-diploma"
  status = 200

[[redirects]]
  from = "/api/statistics"
  to = "/.netlify/functions/statistics"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
